name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        if: always()
        with:
          fetch-depth: 0
      - name: Checkout
        run: |
            docker run --user -0 --volume ${{ github.workspace }}:/src --interactive zricethezav/gitleaks detect --source=/src --verbose --no-git --report-path gitleaks-reports.json \
            cat gitleaks-reports.json \
            pwd \
            ls
      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: gitleaks-reports.json
            
            
            
            
   
       
