name: Gitleaks Secrets Scan
on: [push]
jobs:
  Credentials_Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        run: |
            docker run --user root --volume ${{ github.workspace }}:/src --interactive zricethezav/gitleaks detect --source=/src --verbose --no-git --report-path /src/gitleaks-reports.json
      - name: tade
        if: always()
        run: ls
      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path:  ${{ github.workspace }}/gitleaks-reports.json
          
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
            
            
   
       
