name: Gitleaks Secrets Scan
on: [push]
jobs:
  Credentials_Scanning:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks from container
        run: |
            docker create --name GitLeaksContainer --entrypoint /bin/bash --interactive --volume ${{ github.workspace }}:/src zricethezav/gitleaks 
            docker start GitLeaksContainer
            docker exec GitLeaksContainer git config --global --add safe.directory '/src'
            docker exec --user 1001 GitLeaksContainer id
        continue-on-error: true

      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        with:
          name: Gitleaks Artifact Upload
          path:  ${{ github.workspace }}/gitleaks-reports.json
