name: Secrets and SCA Analysis
on: 
  push:
  workflow_dispatch:
jobs:
  Security_Scanning:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: user privileges
        run: ls -l
      - name: Run Gitleaks from container
        run: |
            docker create --name GitLeaksContainer --user gitleaks --entrypoint /bin/bash --interactive --volume ${{ github.workspace }}:/new_folder zricethezav/gitleaks
            docker start GitLeaksContainer
            docker exec GitLeaksContainer id && docker exec GitLeaksContainer whoami && docker exec GitLeaksContainer ls -l
            docker exec GitLeaksContainer git config --global --add safe.directory '/new_folder'
            docker exec --user $(id -u):$(id -g) GitLeaksContainer bash -c "gitleaks detect --source=/new_folder --verbose --report-path /new_folder/gitleaks-reports.json ; id"
        continue-on-error: true



      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        with:
          name: Gitleaks Artifact Upload
          path:  ${{ github.workspace }}/gitleaks-reports.json
      
      - name: SAST
        run: docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep --config auto > sast-results.json && id
      
      - name: upload_SAST   
        uses: actions/upload-artifact@v3
        with:
          name: SAST Artifact Upload
          path:  ${{ github.workspace }}/sast-results.json
        
          
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired
            
      - name: Upload SCA results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
